name: Build IR Brute Force App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Clone Firmware
        run: git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git
      - name: Copy App
        run: |
          mkdir -p flipperzero-firmware/applications_user/ir_brute_force
          cp -r applications_user/ir_brute_force/* flipperzero-firmware/applications_user/ir_brute_force/
      - name: Register App
        run: echo 'add_subdirectory(ir_brute_force)' >> flipperzero-firmware/applications_user/CMakeLists.txt
      - name: Build App
        run: |
          cd flipperzero-firmware
          ./fbt fap
      - name: Upload FAP
        uses: actions/upload-artifact@v4
        with:
          name: ir_brute_force
          path: flipperzero-firmware/build/f7-firmware-D/.extapps/ir_brute_force.fap